packages:
  -  "packages/api"
  -  "packages/fx-core"
  -  "packages/vscode-extension"
  -  "packages/metrics-ts"
  -  "packages/manifest"
  -  "packages/eslint-plugin-teamsfx"
  -  "packages/tests"
  -  "templates"